# Generated by Django 4.2.1 on 2023-07-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0004_registmodel_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="registmodel",
            name="ac_no",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
