# Generated by Django 4.2.1 on 2023-07-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0006_addamount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registmodel", old_name="ac_no", new_name="ac",
        ),
    ]
