# Generated by Django 4.2.1 on 2023-07-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0008_amountwithdraw"),
    ]

    operations = [
        migrations.RenameModel(old_name="amountwithdraw", new_name="addmoney",),
        migrations.RenameModel(old_name="addamount", new_name="withdrawmoney",),
    ]
