# Generated by Django 4.2.1 on 2023-07-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0010_newsmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsmodel",
            name="content",
            field=models.CharField(max_length=100),
        ),
    ]
