# Generated by Django 4.2.1 on 2023-07-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0011_alter_newsmodel_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="addmoney",
            name="uid",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
