# Generated by Django 4.2.1 on 2023-07-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0012_addmoney_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawmoney",
            name="uid",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
