# Generated by Django 4.2.1 on 2023-07-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0015_remove_newsmodel_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="usernewsmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=50)),
                ("content", models.CharField(max_length=100)),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
