# Generated by Django 4.2.1 on 2023-07-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0017_delete_usernewsmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=50)),
                ("content", models.CharField(max_length=200)),
                ("date", models.DateField()),
            ],
        ),
    ]
