# Generated by Django 4.2.1 on 2023-07-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0019_wishlist_uid"),
    ]

    operations = [
        migrations.RemoveField(model_name="wishlist", name="uid",),
    ]
