# Generated by Django 4.2.1 on 2023-07-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0021_wishlist_newsid"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="uid",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
