# Generated by Django 4.2.1 on 2023-07-26 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0022_wishlist_uid"),
    ]

    operations = [
        migrations.RemoveField(model_name="wishlist", name="newsid",),
        migrations.RemoveField(model_name="wishlist", name="uid",),
    ]
