# Generated by Django 4.2.1 on 2023-08-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0025_wishlist_uid"),
    ]

    operations = [
        migrations.CreateModel(
            name="moneymodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("ac", models.IntegerField()),
                ("amount", models.IntegerField()),
            ],
        ),
    ]
